name: Bikeshare ML Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install black
        run: |
          pip install black
      
      - name: Check code style
        run: |
          black .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Analyzing code using Pylint
        run: |
          pip install pylint
          pylint .

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd bikeshare_project
          pip install -e .
          pip install -r requirements/test_requirements.txt

      - name: Train model
        run: |
          cd bikeshare_project/bikeshare_model
          python train_pipeline.py

      - name: Run tests
        run: |
          cd bikeshare_project
          pytest tests/

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: bikeshare_project/bikeshare_model/trained_models/

  build-package:
    needs: train-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools

      - name: Download model artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts
          path: bikeshare_project/bikeshare_model/trained_models/

      - name: Build package
        run: |
          cd bikeshare_project
          python -m build

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-artifacts
          path: bikeshare_project/dist/

  build-and-push-docker:
    needs: build-package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download model artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts
          path: bikeshare_project/bikeshare_model/trained_models/

      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          name: package-artifacts
          path: bikeshare_project/dist/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./bikeshare_project
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bikeshare-api:latest
