name: Bikeshare ML Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements/test_requirements.txt

      - name: Train model
        run: |
          cd bikeshare_model
          python train_pipeline.py

      - name: Run tests
        run: |
          pytest tests/

      - name: Upload model artifacts
        uses: actions/upload-artifact@v2
        with:
          name: model-artifacts
          path: bikeshare_model/trained_models/

  build-package:
    needs: train-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools

      - name: Download model artifacts
        uses: actions/download-artifact@v2
        with:
          name: model-artifacts
          path: bikeshare_model/trained_models/

      - name: Build package
        run: |
          python -m build

      - name: Upload package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package-artifacts
          path: dist/

  build-and-push-docker:
    needs: build-package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download model artifacts
        uses: actions/download-artifact@v2
        with:
          name: model-artifacts
          path: bikeshare_model/trained_models/

      - name: Download package artifacts
        uses: actions/download-artifact@v2
        with:
          name: package-artifacts
          path: dist/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bikeshare-api:latest
